name: Sync with Fork

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        persist-credentials: false
  
    - name: Sync fork
      uses: tgymnich/fork-sync@v1.8
      with:
        owner: Gernelts
        base: master
        head: main
        repo: gernelts.github.io
        retries: 1
        retry_after: 1
