site_name: Gernelts Wiki
site_url: https://gernelts.wiki

theme:
  name: 'material'
  features:
    - search.highlight
    - search.suggest
    - search.share

plugins:
  - search

docs_dir: ../GerneltsWiki